title: CV | Xavier Cucurull
description:  My resumé
url: https://xaviercucurull.ml
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier
    - jekyll-pdf

exclude:
  - docker-compose.yml
  
